name: logging_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - psycopg2
  - boto3
  - openai
  - pytest
  - pre-commit
  - black
  - isort
  - flake8
  - httpx

