name: Run Tests  # Name of the workflow

on: [push, pull_request]  # Run CI/CD when code is pushed or a PR is opened

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu-based GitHub Actions runner

    steps:
      - name: Checkout repository  # Clone the repo inside the runner
        uses: actions/checkout@v3

      - name: Set up Conda  # Install Miniconda inside GitHub Actions
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: logging_env  # Auto-activate Conda environment
          python-version: 3.10  # Use Python 3.10
          auto-update-conda: true

      - name: Install dependencies  # Install packages using environment.yml
        shell: bash -l {0}  # Ensures commands run inside Conda shell
        run: |
          conda env update --file environment.yml --name logging_env

      - name: Run tests  # Execute tests inside the Conda environment
        shell: bash -l {0}
        run: |
          pytest


